BP-1034 - Subscriber to redis returns nothing
MOV-AI/data-access-layer pull request #162
Opened 2023-06-15 16:53 UTC by erezz-mov-ai

[BP-1034](https://movai.atlassian.net/browse/BP-1034) - Subscriber to redis returns nothing

2023-06-15 16:57 UTC, engdorm commented on dal/classes/protocols/wsredissub.py
> +   - Dor Marcus (dor@mov.ai) - 2023
thanks for the recognition!

2023-06-15 16:59 UTC, engdorm commented on dal/classes/protocols/wsredissub.py
> +                    break
before the break of course 
or even `del connection_queue`
not to create memory leak

2023-06-15 17:05 UTC, engdorm commented on dal/classes/protocols/wsredissub.py
> +            self.tasks[conn_id].append(task)
please init this var in __init__ (self.tasks)

2023-06-15 17:05 UTC, engdorm requested changes
and run black

2023-06-18 10:49 UTC, erezz-mov-ai commented on dal/classes/protocols/wsredissub.py
> +                    break
done

2023-06-18 10:50 UTC, erezz-mov-ai commented on dal/classes/protocols/wsredissub.py
> +            self.tasks[conn_id].append(task)
I have removed the tasks list, it's not necessary

2023-06-18 10:52 UTC, engdorm approved these changes

2023-06-18 10:55 UTC, merged