added Archive interface, refactor gitapi
MOV-AI/data-access-layer pull request #52
Opened 2022-06-16 15:38 UTC by Mograbi

* added BaseArchive
* refactor gitManager to inherit and implement Archive
* moved exceptions module to root -> (/dal)
* reorganized validation files

2022-06-16 17:32 UTC, engdorm requested changes

2022-06-16 17:32 UTC, engdorm commented on dal/api/dalapi.py
> +    schema_folder_path = validation.get_schema_folder(version="2.3")
maybe set it as a global const?
or a class var?
that then the user can get the schema version 
and set a logic around the version 
like
```
if DAL.get_version < "[some breaking version]":
    log.error("please update schema to work with this feature")
    raise UnSupportedVersion("schema version isn't suffiecnt")
```
or something like that

2022-06-16 17:32 UTC, engdorm commented on dal/api/gitapi.py
> +from ..archive.basearchive import BaseArchive
why relative imports and not absolute:
`from dal.api.archive.basearchive import BaseArchive`

2022-06-16 17:32 UTC, engdorm commented on dal/api/gitapi.py
> +    def get_client(**kwargs):
please add docstring 
with all of the different options params for kwargs

2022-06-16 17:32 UTC, engdorm commented on dal/api/gitapi.py
> +        if obj_name.find('json') == -1:
change to 
`json in obj_name`

2022-06-16 17:32 UTC, engdorm commented on dal/api/gitapi.py
> +        if obj_name.find('json') == -1:
and maybe even only if it's on the end 
(because you wanna check it the name of the file include it's type right?)
so 
`if obj_name[-5:] != ".json":`

2022-06-16 17:32 UTC, engdorm commented on dal/api/gitapi.py
> +        if obj_name.find('json') == -1:
and final comment about it 
I think that the flow files 
will have a .flo ending 
need to check it 
either way, you need to be sure about the ending 
and that there isn't any "." in the file name without json
like 
```
if '.' in obj_name:
   f_type = obj_name.split('.')[-1]
   if f_type not in ['json', 'flo', 'node', 'py']:
       log.error(f"not supported type {f_type}")

2022-06-16 17:32 UTC, engdorm commented on dal/archive/basearchive.py
> +        pass
leave empty abstract method
(remove the pass)

2022-06-16 17:32 UTC, engdorm commented on dal/archive/basearchive.py
> +        pass
leave empty abstract method
(remove the pass)

2022-06-16 17:32 UTC, engdorm commented on dal/archive/basearchive.py
> +        pass
leave empty abstract method
(remove the pass)

2022-06-16 17:32 UTC, engdorm commented on dal/validation/schema/2.3/annotation.schema.json
> +    "$id": "AnnotationSchema-2.3",
maybe align to the version ("3.1")?

2022-06-20 08:10 UTC, Mograbi commented on dal/validation/schema/2.3/annotation.schema.json
> +    "$id": "AnnotationSchema-2.3",
currently those are schemas for 2.3 and 2.1
there should be new folder and files for schemas >= 3.0

2022-06-20 10:13 UTC, Mograbi commented on dal/api/gitapi.py
>          Args:
I think I need to remove them, not used basically

2022-06-20 11:25 UTC, Mograbi commented on dal/api/gitapi.py
> +        if obj_name.find('json') == -1:
not exactly,
I want to check if the name has .json at the end because files in git mainly (config files) for node/flow/callbacks/,... are named <name>.json
so in case user asked for flow1 without the ".json" I add it manually

2022-06-20 11:26 UTC, Mograbi commented on dal/api/gitapi.py
> +        if obj_name.find('json') == -1:
but that make sense,
I will mark it currently as TODO and change it later

2022-07-11 10:37 UTC, engdorm approved these changes

2022-07-11 10:37 UTC, engdorm commented on README.md
> +    py3rosmsgs
why you don't mention a version 
maybe you can mention the least workable

2022-07-11 10:37 UTC, engdorm commented on README.md
> +    pyros-genmsg
why you don't mention a version
maybe you can mention the least workable

2022-07-11 10:37 UTC, engdorm commented on dal/classes/common/gitlink.py
> +class GitLink:
maybe add a method to check that git can connect to this server?

2022-07-11 11:15 UTC, Mograbi commented on dal/classes/common/gitlink.py
> +class GitLink:
it's just agit link parser

2022-07-11 11:16 UTC, Mograbi commented on README.md
> +    py3rosmsgs
will add

2022-09-22 12:21 UTC, closed without merging