Feature bp 728 migrate movai classes to use data access layer
MOV-AI/data-access-layer pull request #57
Opened 2022-09-08 06:40 UTC by erezz-mov-ai

This branch contain all necessary changed in data-access-layer to support the split of movai_classes

jira:
https://movai.atlassian.net/browse/BP-728?atlOrigin=eyJpIjoiMWRmY2MyY2ZjNTk2NGE5MWE2YWYxMTg4Nzk4Y2U0N2YiLCJwIjoiaiJ9

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-09-08 14:15 UTC, engdorm commented
@erezz-mov-ai this P.R breaks the pipeline

2022-09-11 11:24 UTC, Mograbi requested changes

2022-09-11 11:24 UTC, Mograbi commented on dal/data/tree.py
> +from dal.data.mixins import ChildrenCmpMixin, ValueCmpMixin
sometimes importing from module that you are already in causes  problems,
make sure this does not cause issues

2022-09-11 11:24 UTC, Mograbi commented on dal/data/workspace.py
> +from dal.data.persistence import Persistence
same as previous

2022-09-11 11:24 UTC, Mograbi commented on dal/helpers/flow/__init__.py
> +from .gflow import GFlow
do we need that ?

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/callback.py
> +from dal.scopes.scope import Scope
scopes is a module which include Scope

doing ``` from dal.scopes import Scope```
make more sense and neater, or we delete the __init__ file from scopes
@engdorm what do you think ?

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/graphicscenevalue.py
> +"""
graphicscene as I remember should be part of enterprise edition ? @engdorm , not sure
here this information (or part of graphicscene ) will be public

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/node.py
> +LOGGER = Log.get_logger(__name__)
why changed to name ?
if node got imported from other module, then the __name__ will be according to that module and not Node.

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/package.py
> +from dal.scopes.scope import Scope
same as before, scopes is a module which already includes all of the classes under
in case there was a change inside the files/folders in scopes then you need to change all of this again 
so doing ```from dal.scopes import Scope``` saves a lot of time in case there was changes need to be done in scopes files structure

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/ports.py
> +from dal.scopes.scope import Scope
same

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/robot.py
> +from dal.scopes.scope import Scope
same

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/statemachine.py
> +from dal.scopes.scope import Scope
same

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/system.py
> +from dal.scopes.scope import Scope
same

2022-09-11 11:24 UTC, Mograbi commented on dal/scopes/widget.py
> +from dal.scopes.scope import Scope
same

2022-09-11 13:14 UTC, engdorm commented on dal/classes/protocols/redissub.py
> +from dal.scopes.robot import Robot
agree, it's preferred

2022-09-21 13:40 UTC, Mograbi requested changes

2022-09-21 13:40 UTC, Mograbi commented on dal/models/flow.py
>  from dal.scopes.scopestree import scopes
I moved the scopestree to models as it's not related to scopes
please update it to ```from dal.models.scopestree import scopes```

2022-09-21 13:40 UTC, Mograbi commented on dal/models/role.py
> +from dal.scopes.scopestree import scopes
scopestree moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/models/user.py
> +from dal.scopes.scopestree import ScopesTree, scopes
scopestree moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/scopes/flowlinks.py
> +from dal.scopes.scopestree import ScopePropertyNode, ScopeNode, scopes
scopestree moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/classes/utils/acl.py
> +from dal.scopes.scopestree import ScopesTree, scopes
scopestree moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/models/baseuser.py
> +from dal.scopes.scopestree import ScopesTree, scopes
scopestree moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/models/flow.py
> +from dal.scopes.flowlinks import FlowLinks
flowlinks moved to models

2022-09-21 13:40 UTC, Mograbi commented on dal/models/node.py
>  from dal.scopes.scopestree import scopes
scopestree moved to models

2022-09-22 08:42 UTC, erezz-mov-ai commented on dal/models/graphicscenevalue.py
this file should be inside movai_core_enterprise

2022-09-22 08:51 UTC, Mograbi approved these changes

2022-09-22 10:56 UTC, merged