Feat : 2.4.0 release
MOV-AI/data-access-layer pull request #72
Opened 2022-11-10 14:04 UTC by erezz-mov-ai

this branch contains the necessary changes for the updated split

jira:
https://movai.atlassian.net/browse/BP-830?atlOrigin=eyJpIjoiMDMzODQwZjI4OTc1NDYwMGFlNjUyOTcwMGJlNjM0MDIiLCJwIjoiaiJ9

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
'- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue'

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-11-10 17:04 UTC, engdorm approved these changes

2022-11-16 17:13 UTC, AlexFernandes-MOVAI requested changes
please add prefix for entrypoints

2022-11-16 17:13 UTC, AlexFernandes-MOVAI commented on setup.py
> +             "backup = dal.tools.backup:main",
might be better to add a prefix like : `movai_backup` or `dal_backup`

2022-11-16 17:17 UTC, AlexFernandes-MOVAI commented on setup.py
> +             "backup = dal.tools.backup:main",
easily testable with :
- `python3 setup.py build`
- `sudo python3 setup.py install`

there you will end up with a `backup` command:
```
cat /usr/local/bin/backup
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'dal==1.0.1.post0','console_scripts','backup'
__requires__ = 'dal==1.0.1.post0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('dal==1.0.1.post0', 'console_scripts', 'backup')()
    )
```

2022-11-17 11:16 UTC, erezz-mov-ai commented on setup.py
> +             "backup = dal.tools.backup:main",
done!

2022-11-17 12:04 UTC, engdorm requested changes

2022-11-17 12:04 UTC, engdorm commented on setup.py
> +             "dal_backup = dal.tools.da_backup:main",
dal.tools.da_backup -> dal.tools.dal_backup

2022-11-17 14:50 UTC, AlexFernandes-MOVAI requested changes

2022-11-17 14:50 UTC, AlexFernandes-MOVAI commented on setup.py
> +    "movai_core_shared==2.4.0.1"
let's use something like : `"movai_core_shared==2.4.*"`

2022-11-20 08:13 UTC, engdorm approved these changes

2022-12-21 09:59 UTC, AlexFernandes-MOVAI approved these changes

2023-01-08 12:23 UTC, closed without merging